### ISSUE TITLE
Subspectrum Fit Error

### ISSUE THREAD

**Issue by elliesch** [astropy/specutils#586]
I'm running a fit on a subspectrum, following the specutils tutorial [here](https://specutils.readthedocs.io/en/stable/fitting.html).

This is the code routine that I'm using:
```python
from astropy.modeling import models
from astropy import units as u
from specutils.spectra import Spectrum1D
from specutils.fitting import fit_lines

spectrum = Spectrum1D(flux=flux*u.Jy, spectral_axis=lambda*u.angstrom,
                      rest_value=6561.16*u.angstrom)
sub_region = SpectralRegion(6490*u.angstrom, 6635*u.angstrom)
sub_spectrum = extract_region(spectrum, sub_region)

g_init = models.Gaussian1D(amplitude=1*u.Jy, mean=6561.157*u.angstrom, 
                           stddev=4.0721*u.angstrom)
g_fit = fit_lines(sub_spectrum, g_init)
y_fit = g_fit(sub_spectrum.spectral_axis)
```

This code snippet worked on 12/5/19. Since then I have updated both astropy to version 4.0 and specutils to 7.0, but I'm not sure what versions I had on 12/5/19. When running it now I get the following error on `g_fit`:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-86-cd94dcaa50ee> in <module>
     21 
     22 
---> 23 g_fit = fit_lines(sub_spectrum, g_init)
     24 y_fit = g_fit(sub_spectrum.spectral_axis)
     25 

~/opt/anaconda3/lib/python3.7/site-packages/specutils/fitting/fitmodels.py in fit_lines(spectrum, model, fitter, exclude_regions, weights, window, **kwargs)
    364         fit_model = _fit_lines(spectrum, model_guess, fitter,
    365                                exclude_regions, weights, model_window,
--> 366                                ignore_units, **kwargs)
    367         if model_guess.name is not None:
    368             fit_model.name = model_guess.name

~/opt/anaconda3/lib/python3.7/site-packages/specutils/fitting/fitmodels.py in _fit_lines(spectrum, model, fitter, exclude_regions, weights, window, ignore_units, **kwargs)
    485         spectral_axis=dispersion.value * dispersion_unit,
    486         wcs=input_spectrum.wcs,
--> 487         velocity_convention=input_spectrum.velocity_convention,
    488         rest_value=input_spectrum.rest_value)
    489 

~/opt/anaconda3/lib/python3.7/site-packages/specutils/spectra/spectrum_mixin.py in velocity_convention(self)
    146         Returns the velocity convention
    147         """
--> 148         return self._velocity_convention
    149 
    150     def with_velocity_convention(self, velocity_convention):

AttributeError: 'Spectrum1D' object has no attribute '_velocity_convention'
```

I am working with Python 3.7 in Jupyter.

**Comment by nmearl** [comment]
@ellisch Thanks for opening an issue about this! I can confirm the issue, and we're looking into it now.

**Comment by elliesch** [comment]
Thanks @nmearl!

**Comment by eteq** [comment]
Fixed in #593.  Thanks for reporting, @elliesch !

**Comment by elliesch** [comment]
Thanks for fixing it! 🥇
