### PR TITLE
TST: Pin casa-formats-io in oldest-deps

### LINKED ISSUE #1091: TST: oldest deps job failed because something is forcing numpy upgrade to 1.24
Example log: https://github.com/astropy/specutils/actions/runs/6634110439/job/18023023740

```
INTERNALERROR> AttributeError: module 'numpy' has no attribute 'typeDict'
```

Your current requirements:

https://github.com/astropy/specutils/blob/368cfbd3d8fd2c251d86f8038052c346825280fb/setup.cfg#L19-L26

Your current oldest deps setup:

https://github.com/astropy/specutils/blob/368cfbd3d8fd2c251d86f8038052c346825280fb/tox.ini#L42-L52

What is actually installed:

```
numpy==1.24.4
scipy==1.3.3
```

Your options:

1. Hunt the culprit down and pin that too in oldest deps.
2. Admit defeat and bump your minversions and oldest deps pins to match.

### PR DESCRIPTION
**Pull request by pllim**
Pin casa-formats-io in oldest-deps job because it is upgrading numpy but we do not want that to happen.

Fix #1091

### CODE REVIEW

**Comment by keflavich** [comment]
@astrofrog can you comment on casa-formats-io & numpy versioning?

**Comment by astrofrog** [comment]
Will look soon!

**Comment by pllim** [comment]
Introduced in https://github.com/radio-astro-tools/casa-formats-io/pull/57

**Comment by astrofrog** [comment]
Maybe specutils needs to bump the minimum version of Numpy? Astropy core requires Numpy 1.22+. Requiring 1.21 in casa-formats-io seems reasonable.

**Comment by pllim** [comment]
That is not my call to make. You can see in the `tox.ini` here that I already have to pin a bunch of other stuff to keep the oldest deps job alive. I just want it to be green so it would stop spamming me.

Bumping required dependencies fall to specutils maintainers.
